"""add case emergency contact

Revision ID: 137b46a7e768
Revises: e779724a1146
Create Date: 2026-07-10 22:00:07.236615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137b46a7e768'
down_revision: Union[str, Sequence[str], None] = 'e779724a1146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'emergency_contact_phone')
    op.drop_column('cases', 'emergency_contact_name')
    # ### end Alembic commands ###
