"""add scheduled reminders

Revision ID: 1b0581fc4e9c
Revises: 927669cf1a68
Create Date: 2026-07-08 05:02:11.157821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0581fc4e9c'
down_revision: Union[str, Sequence[str], None] = '927669cf1a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_reminders', sa.Column('status', sa.String(), nullable=False))
    op.add_column('scheduled_reminders', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_reminders', 'created_at')
    op.drop_column('scheduled_reminders', 'status')
    # ### end Alembic commands ###
