"""add fda warnings

Revision ID: 3f6f9d83388b
Revises: 1cee36bcbdad
Create Date: 2026-07-10 21:26:30.941039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6f9d83388b'
down_revision: Union[str, Sequence[str], None] = '1cee36bcbdad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fda_warnings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'dismissed', name='fdawarningstatus'), nullable=False),
    sa.Column('source_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fda_warnings_drug_name'), 'fda_warnings', ['drug_name'], unique=False)
    op.create_table('case_fda_warnings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('fda_warning_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['fda_warning_id'], ['fda_warnings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_fda_warnings')
    op.drop_index(op.f('ix_fda_warnings_drug_name'), table_name='fda_warnings')
    op.drop_table('fda_warnings')
    # ### end Alembic commands ###
