"""add wiki articles

Revision ID: e779724a1146
Revises: 3f6f9d83388b
Create Date: 2026-07-10 21:53:44.020567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e779724a1146'
down_revision: Union[str, Sequence[str], None] = '3f6f9d83388b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('surgery_type', sa.String(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', name='wikiarticlestatus'), nullable=False),
    sa.Column('source_case_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_articles_surgery_type'), 'wiki_articles', ['surgery_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wiki_articles_surgery_type'), table_name='wiki_articles')
    op.drop_table('wiki_articles')
    # ### end Alembic commands ###
